### ISSUE TITLE
对源代码文件类型检测有误

### ISSUE THREAD

**Issue by TooYoungTooSimp** [hr567/hsyoj#2]
[这一行对.cc文件检测有误](https://github.com/hr567/hsyoj/blob/c70015122eec9d3904ef6b5ba7cc686f38791c77/judge/judge.py#L79)
![image](https://user-images.githubusercontent.com/6648049/29823935-b40845da-8d02-11e7-9d02-981d3b0f4fb4.png)

**Comment by hr567** [comment]
嗯，一会儿就改过来

**Comment by TooYoungTooSimp** [comment]
我来交个pull request玩

**Comment by TooYoungTooSimp** [comment]
看来这个问题解决了
